[build]
builder = "nixpacks"

[deploy]
startCommand = "uvicorn backend.main:app --host 0.0.0.0 --port $PORT"

[[services]]
name = "resume-optimizer-backend"
type = "web"

[env]
PORT = "8000"
PYTHON_VERSION = "3.11"